---
- hosts: all
  become: true
  tasks:
  - name: Set hostname to node
    ansible.builtin.hostname:
      name: "{{ hostname }}"
      use: systemd
    register: set_hostname

  - name: Configure Kubernetes Network
    block:
      - name: Ensure Network modules
        community.general.modprobe:
          name: "{{ item }}"
          state: present
        loop:
          - overlay
          - br_netfilter

  - name: Enable Kubernetes Services
    block:
      - name: Start CRI-O
        ansible.builtin.service:
          name: crio
          daemon_reload: true
          state: started
          enabled: true

      - name: Enable Kubelet
        ansible.builtin.service:
          name: kubelet
          daemon_reload: true
          enabled: true

  - name: Token Join for worker nodes
    block:
      - name: Copy the join command to server location
        ansible.builtin.copy:
          src: join-command
          dest: /tmp/join-command.sh 
          mode: 0777
        register: token_kubeadm

      - name: Join the node to cluster
        ansible.builtin.command: sh /tmp/join-command.sh
        when: token_kubeadm is changed

      - name: Wait kubelet
        ansible.builtin.pause:
          seconds: 20